config/routes.rb
Rails.application.routes.draw do

  resources :weekly_reports

  resources :daily_reports

  resources :tasks

  resources :skills

  resources :objectives

end

app/models/objective.rb
class Objective < ActiveRecord::Base
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: [:show, :edit, :update, :destroy]

  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit
  end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to @objective, notice: 'Objective was successfully created.' }
        format.json { render :show, status: :created, location: @objective }
      else
        format.html { render :new }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1
  # PATCH/PUT /objectives/1.json
  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to @objective, notice: 'Objective was successfully updated.' }
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    @objective.destroy
    respond_to do |format|
      format.html { redirect_to objectives_url, notice: 'Objective was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objective_params
      params[:objective]
    end
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.erb
<%= form_for(@objective) do |f| %>
  <% if @objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
      <% @objective.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/objectives/edit.html.erb
<h1>Editing objective</h1>

<%= render 'form' %>

<%= link_to 'Show', @objective %> |
<%= link_to 'Back', objectives_path %>

app/views/objectives/index.html.erb
<h1>Listing objectives</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @objectives.each do |objective| %>
      <tr>
        <td><%= link_to 'Show', objective %></td>
        <td><%= link_to 'Edit', edit_objective_path(objective) %></td>
        <td><%= link_to 'Destroy', objective, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Objective', new_objective_path %>

app/views/objectives/new.html.erb
<h1>New objective</h1>

<%= render 'form' %>

<%= link_to 'Back', objectives_path %>

app/views/objectives/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_objective_path(@objective) %> |
<%= link_to 'Back', objectives_path %>