config/routes.rb
Rails.application.routes.draw do

  resources :weekly_reports

  resources :daily_reports

  resources :tasks

  resources :skills

  resources :objectives

end

app/models/daily_report.rb
class DailyReport < ActiveRecord::Base
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :set_daily_report, only: [:show, :edit, :update, :destroy]

  # GET /daily_reports
  # GET /daily_reports.json
  def index
    @daily_reports = DailyReport.all
  end

  # GET /daily_reports/1
  # GET /daily_reports/1.json
  def show
  end

  # GET /daily_reports/new
  def new
    @daily_report = DailyReport.new
  end

  # GET /daily_reports/1/edit
  def edit
  end

  # POST /daily_reports
  # POST /daily_reports.json
  def create
    @daily_report = DailyReport.new(daily_report_params)

    respond_to do |format|
      if @daily_report.save
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully created.' }
        format.json { render :show, status: :created, location: @daily_report }
      else
        format.html { render :new }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_reports/1
  # PATCH/PUT /daily_reports/1.json
  def update
    respond_to do |format|
      if @daily_report.update(daily_report_params)
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_report }
      else
        format.html { render :edit }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_reports/1
  # DELETE /daily_reports/1.json
  def destroy
    @daily_report.destroy
    respond_to do |format|
      format.html { redirect_to daily_reports_url, notice: 'Daily report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_report
      @daily_report = DailyReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_report_params
      params[:daily_report]
    end
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/views/daily_reports/_form.html.erb
<%= form_for(@daily_report) do |f| %>
  <% if @daily_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@daily_report.errors.count, "error") %> prohibited this daily_report from being saved:</h2>

      <ul>
      <% @daily_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/daily_reports/edit.html.erb
<h1>Editing daily_report</h1>

<%= render 'form' %>

<%= link_to 'Show', @daily_report %> |
<%= link_to 'Back', daily_reports_path %>

app/views/daily_reports/index.html.erb
<h1>Listing daily_reports</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_reports.each do |daily_report| %>
      <tr>
        <td><%= link_to 'Show', daily_report %></td>
        <td><%= link_to 'Edit', edit_daily_report_path(daily_report) %></td>
        <td><%= link_to 'Destroy', daily_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily report', new_daily_report_path %>

app/views/daily_reports/new.html.erb
<h1>New daily_report</h1>

<%= render 'form' %>

<%= link_to 'Back', daily_reports_path %>

app/views/daily_reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_daily_report_path(@daily_report) %> |
<%= link_to 'Back', daily_reports_path %>